### ISSUE TITLE
Not compatible with fast api > 137 

### ISSUE THREAD

**Issue by valentingarreau-del** [alexschimpf/fastapi-versionizer#74]
When i update fastapi to 140 got this error :

ImportError while loading conftest '/home/runner/work/***/***/****/***/tests/conftest.py'.
tests/conftest.py:23: in <module>
    from spark_ai.api_consumer.main import app
src/***/***/main.py:81: in <module>
    versions = Versionizer(
../../.venv/lib/python3.14/site-packages/fastapi_versionizer/versionizer.py:105: in __init__
    self._strip_routes()
../../.venv/lib/python3.14/site-packages/fastapi_versionizer/versionizer.py:366: in _strip_routes
    getattr(route, 'path') in paths_to_keep
    ^^^^^^^^^^^^^^^^^^^^^^
E   AttributeError: '_IncludedRouter' object has no attribute 'path'

Look like `_IncludedRouter` is used for old version of fastapi

https://github.com/fastapi/fastapi/discussions/15782

can we get an update please ?

**Comment by mat81black** [comment]
Hi,

I ran into a similar class of issues while working on API versioning with more recent versions of FastAPI.

Since there haven't been recent updates on this repository, I'm sharing this experience in case it helps anyone blocked by this issue and considering a migration.

In the meantime, I'm maintaining an alternative that I use in my own projects:
https://github.com/mat81black/fastapi-router-versioning

Disclaimer: I'm the author of the package. The public repository is relatively new, but I've been using this approach internally for about a year.

The main difference is that versioning starts from `APIRouter` instances, instead of wrapping the entire FastAPI application. This way, the main app instance stays untouched, including middleware, lifespan, CORS, and other global configuration.

It also avoids having to inspect `app.routes` at runtime, which seems to be one of the points that became problematic with more recent FastAPI versions.

I don't consider it an official fix for this repository, nor a drop-in replacement. I'm just sharing it as a possible alternative for anyone already evaluating a migration.

As for compatibility, the package supports FastAPI `>=0.120.0`, with the exception of versions `0.137.0` and `0.137.1`. I deliberately chose to exclude these two intermediate releases: `0.137.0` changed FastAPI's internal routing structure, while `iter_route_contexts()` became available starting with `0.137.2` for the more advanced use cases that previously required access to `router.routes`. I preferred not to introduce code specific to handling just these two transitional versions.

I hope this helps anyone landing on this issue. If third-party alternatives aren't appropriate for this repository, feel free to hide or remove the comment.
